import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter", //"--font-geist-sans",
});

export const metadata: Metadata = {
  title: "Color picker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="flex flex-col min-h-screen bg-primary/5">
          <Header />
          <main className="pt-16 w-full h-full px-8 md:px-16 lg:px-32">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
